# Lab | Transformers

---

**Note: for GPU acceleration, run this notebook in [Google Colab](https://colab.research.google.com/).**



### Section structure

1. The open-source ecosystem: increasing accessibility to machine learning (ML) software and hardware
2. Some simple code demonstrations
3. Q&A

## 1. Ease-of-use: Using Transformers in 3 lines of code


**Overview of different tasks that can be automated with ML**
* Key ingredients: (1) a model trained on a specific task; (2) input data (e.g. texts or images); (3) output produced by the model.
* Transformers are currently the most popular type of deep learning algorithm. Most tasks below are solved with Transformers. There might be other types of algorithms coming up in the medium term.

**Install the Transformers library & dependencies**

In [2]:
!pip install transformers  # The Transformers library from Hugging Face
!pip install sentencepiece
!pip install wikipedia
!pip install accelerate
!pip install tf-keras
!pip install torch

# note: you might need to restart you jupyter kernel after installing the libraries

ERROR: Invalid requirement: '#': Expected package name at the start of dependency specifier
    #
    ^

Requirement already satisfied: sentencepiece in c:\users\nicol\appdata\local\programs\python\python312\lib\site-packages (0.2.1)
Requirement already satisfied: wikipedia in c:\users\nicol\appdata\local\programs\python\python312\lib\site-packages (1.4.0)
Requirement already satisfied: beautifulsoup4 in c:\users\nicol\appdata\local\programs\python\python312\lib\site-packages (from wikipedia) (4.12.3)
Requirement already satisfied: requests<3.0.0,>=2.0.0 in c:\users\nicol\appdata\local\programs\python\python312\lib\site-packages (from wikipedia) (2.32.3)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\nicol\appdata\local\programs\python\python312\lib\site-packages (from requests<3.0.0,>=2.0.0->wikipedia) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\nicol\appdata\local\programs\python\python312\lib\site-packages (from requests<3.0.0,>=2.0.0->wikipedia) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\nicol\appdata\local\programs\python\python312\lib\site-packages (from requests<3.0.0,>=2.0.0->wikipedia) (2.2.2)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\nicol\appdata\local\programs\python\python312\lib\site-packages (from requests<3.0.0,>=2.0.0->wikipedia) (2024.7.4)
Requirement already satisfied: soupsieve>1.2 in c:\users\nicol\appdata\local\programs\python\python312\lib\site-packages (from beautifulsoup4->wikipedia) (2.5)
Requirement already satisfied: accelerate in c:\users\nicol\appdata\local\programs\python\python312\lib\site-packages (1.8.1)
Requirement already satisfied: numpy<3.0.0,>=1.17 in c:\users\nicol\appdata\local\programs\python\python312\lib\site-packages (from accelerate) (2.1.3)
Requirement already satisfied: packaging>=20.0 in c:\users\nicol\appdata\local\programs\python\python312\lib\site-packages (from accelerate) (24.1)
Requirement already satisfied: psutil in c:\users\nicol\appdata\local\programs\python\python312\lib\site-packages (from accelerate) (6.0.0)
Requirement already satisfied: pyyaml in c:\users\nicol\appdata\local\programs\python\python312\lib\site-packages (from accelerate) (6.0.1)
Requirement already satisfied: torch>=2.0.0 in c:\users\nicol\appdata\local\programs\python\python312\lib\site-packages (from accelerate) (2.7.1)
Requirement already satisfied: huggingface_hub>=0.21.0 in c:\users\nicol\appdata\local\programs\python\python312\lib\site-packages (from accelerate) (0.25.2)
Requirement already satisfied: safetensors>=0.4.3 in c:\users\nicol\appdata\local\programs\python\python312\lib\site-packages (from accelerate) (0.5.3)
Requirement already satisfied: filelock in c:\users\nicol\appdata\local\programs\python\python312\lib\site-packages (from huggingface_hub>=0.21.0->accelerate) (3.18.0)
Requirement already satisfied: fsspec>=2023.5.0 in c:\users\nicol\appdata\local\programs\python\python312\lib\site-packages (from huggingface_hub>=0.21.0->accelerate) (2025.5.1)
Requirement already satisfied: requests in c:\users\nicol\appdata\local\programs\python\python312\lib\site-packages (from huggingface_hub>=0.21.0->accelerate) (2.32.3)
Requirement already satisfied: tqdm>=4.42.1 in c:\users\nicol\appdata\local\programs\python\python312\lib\site-packages (from huggingface_hub>=0.21.0->accelerate) (4.67.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in c:\users\nicol\appdata\local\programs\python\python312\lib\site-packages (from huggingface_hub>=0.21.0->accelerate) (4.12.2)
Requirement already satisfied: sympy>=1.13.3 in c:\users\nicol\appdata\local\programs\python\python312\lib\site-packages (from torch>=2.0.0->accelerate) (1.14.0)
Requirement already satisfied: networkx in c:\users\nicol\appdata\local\programs\python\python312\lib\site-packages (from torch>=2.0.0->accelerate) (3.5)
Requirement already satisfied: jinja2 in c:\users\nicol\appdata\local\programs\python\python312\lib\site-packages (from torch>=2.0.0->accelerate) (3.1.4)
Requirement already satisfied: setuptools in c:\users\nicol\appdata\local\programs\python\python312\lib\site-packages (from torch>=2.0.0->accelerate) (70.2.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\nicol\appdata\local\programs\python\python312\lib\site-packages (from sympy>=1.13.3->torch>=2.0.0->accelerate) (1.3.0)
Requirement already satisfied: colorama in c:\users\nicol\appdata\local\programs\python\python312\lib\site-packages (from tqdm>=4.42.1->huggingface_hub>=0.21.0->accelerate) (0.4.6)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\nicol\appdata\local\programs\python\python312\lib\site-packages (from jinja2->torch>=2.0.0->accelerate) (2.1.5)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\nicol\appdata\local\programs\python\python312\lib\site-packages (from requests->huggingface_hub>=0.21.0->accelerate) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\nicol\appdata\local\programs\python\python312\lib\site-packages (from requests->huggingface_hub>=0.21.0->accelerate) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\nicol\appdata\local\programs\python\python312\lib\site-packages (from requests->huggingface_hub>=0.21.0->accelerate) (2.2.2)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\nicol\appdata\local\programs\python\python312\lib\site-packages (from requests->huggingface_hub>=0.21.0->accelerate) (2024.7.4)
Requirement already satisfied: tf-keras in c:\users\nicol\appdata\local\programs\python\python312\lib\site-packages (2.19.0)
Requirement already satisfied: tensorflow<2.20,>=2.19 in c:\users\nicol\appdata\local\programs\python\python312\lib\site-packages (from tf-keras) (2.19.0)
Requirement already satisfied: absl-py>=1.0.0 in c:\users\nicol\appdata\local\programs\python\python312\lib\site-packages (from tensorflow<2.20,>=2.19->tf-keras) (2.3.1)
Requirement already satisfied: astunparse>=1.6.0 in c:\users\nicol\appdata\local\programs\python\python312\lib\site-packages (from tensorflow<2.20,>=2.19->tf-keras) (1.6.3)
Requirement already satisfied: flatbuffers>=24.3.25 in c:\users\nicol\appdata\local\programs\python\python312\lib\site-packages (from tensorflow<2.20,>=2.19->tf-keras) (25.2.10)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in c:\users\nicol\appdata\local\programs\python\python312\lib\site-packages (from tensorflow<2.20,>=2.19->tf-keras) (0.6.0)
Requirement already satisfied: google-pasta>=0.1.1 in c:\users\nicol\appdata\local\programs\python\python312\lib\site-packages (from tensorflow<2.20,>=2.19->tf-keras) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in c:\users\nicol\appdata\local\programs\python\python312\lib\site-packages (from tensorflow<2.20,>=2.19->tf-keras) (18.1.1)
Requirement already satisfied: opt-einsum>=2.3.2 in c:\users\nicol\appdata\local\programs\python\python312\lib\site-packages (from tensorflow<2.20,>=2.19->tf-keras) (3.4.0)
Requirement already satisfied: packaging in c:\users\nicol\appdata\local\programs\python\python312\lib\site-packages (from tensorflow<2.20,>=2.19->tf-keras) (24.1)
Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.3 in c:\users\nicol\appdata\local\programs\python\python312\lib\site-packages (from tensorflow<2.20,>=2.19->tf-keras) (5.29.5)
Requirement already satisfied: requests<3,>=2.21.0 in c:\users\nicol\appdata\local\programs\python\python312\lib\site-packages (from tensorflow<2.20,>=2.19->tf-keras) (2.32.3)
Requirement already satisfied: setuptools in c:\users\nicol\appdata\local\programs\python\python312\lib\site-packages (from tensorflow<2.20,>=2.19->tf-keras) (70.2.0)
Requirement already satisfied: six>=1.12.0 in c:\users\nicol\appdata\local\programs\python\python312\lib\site-packages (from tensorflow<2.20,>=2.19->tf-keras) (1.16.0)
Requirement already satisfied: termcolor>=1.1.0 in c:\users\nicol\appdata\local\programs\python\python312\lib\site-packages (from tensorflow<2.20,>=2.19->tf-keras) (3.1.0)
Requirement already satisfied: typing-extensions>=3.6.6 in c:\users\nicol\appdata\local\programs\python\python312\lib\site-packages (from tensorflow<2.20,>=2.19->tf-keras) (4.12.2)
Requirement already satisfied: wrapt>=1.11.0 in c:\users\nicol\appdata\local\programs\python\python312\lib\site-packages (from tensorflow<2.20,>=2.19->tf-keras) (1.17.2)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in c:\users\nicol\appdata\local\programs\python\python312\lib\site-packages (from tensorflow<2.20,>=2.19->tf-keras) (1.74.0)
Requirement already satisfied: tensorboard~=2.19.0 in c:\users\nicol\appdata\local\programs\python\python312\lib\site-packages (from tensorflow<2.20,>=2.19->tf-keras) (2.19.0)
Requirement already satisfied: keras>=3.5.0 in c:\users\nicol\appdata\local\programs\python\python312\lib\site-packages (from tensorflow<2.20,>=2.19->tf-keras) (3.11.1)
Requirement already satisfied: numpy<2.2.0,>=1.26.0 in c:\users\nicol\appdata\local\programs\python\python312\lib\site-packages (from tensorflow<2.20,>=2.19->tf-keras) (2.1.3)
Requirement already satisfied: h5py>=3.11.0 in c:\users\nicol\appdata\local\programs\python\python312\lib\site-packages (from tensorflow<2.20,>=2.19->tf-keras) (3.14.0)
Requirement already satisfied: ml-dtypes<1.0.0,>=0.5.1 in c:\users\nicol\appdata\local\programs\python\python312\lib\site-packages (from tensorflow<2.20,>=2.19->tf-keras) (0.5.3)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\nicol\appdata\local\programs\python\python312\lib\site-packages (from requests<3,>=2.21.0->tensorflow<2.20,>=2.19->tf-keras) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\nicol\appdata\local\programs\python\python312\lib\site-packages (from requests<3,>=2.21.0->tensorflow<2.20,>=2.19->tf-keras) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\nicol\appdata\local\programs\python\python312\lib\site-packages (from requests<3,>=2.21.0->tensorflow<2.20,>=2.19->tf-keras) (2.2.2)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\nicol\appdata\local\programs\python\python312\lib\site-packages (from requests<3,>=2.21.0->tensorflow<2.20,>=2.19->tf-keras) (2024.7.4)
Requirement already satisfied: markdown>=2.6.8 in c:\users\nicol\appdata\local\programs\python\python312\lib\site-packages (from tensorboard~=2.19.0->tensorflow<2.20,>=2.19->tf-keras) (3.8.2)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in c:\users\nicol\appdata\local\programs\python\python312\lib\site-packages (from tensorboard~=2.19.0->tensorflow<2.20,>=2.19->tf-keras) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in c:\users\nicol\appdata\local\programs\python\python312\lib\site-packages (from tensorboard~=2.19.0->tensorflow<2.20,>=2.19->tf-keras) (3.1.3)
Requirement already satisfied: wheel<1.0,>=0.23.0 in c:\users\nicol\appdata\local\programs\python\python312\lib\site-packages (from astunparse>=1.6.0->tensorflow<2.20,>=2.19->tf-keras) (0.45.1)
Requirement already satisfied: rich in c:\users\nicol\appdata\local\programs\python\python312\lib\site-packages (from keras>=3.5.0->tensorflow<2.20,>=2.19->tf-keras) (14.0.0)
Requirement already satisfied: namex in c:\users\nicol\appdata\local\programs\python\python312\lib\site-packages (from keras>=3.5.0->tensorflow<2.20,>=2.19->tf-keras) (0.1.0)
Requirement already satisfied: optree in c:\users\nicol\appdata\local\programs\python\python312\lib\site-packages (from keras>=3.5.0->tensorflow<2.20,>=2.19->tf-keras) (0.17.0)
Requirement already satisfied: MarkupSafe>=2.1.1 in c:\users\nicol\appdata\local\programs\python\python312\lib\site-packages (from werkzeug>=1.0.1->tensorboard~=2.19.0->tensorflow<2.20,>=2.19->tf-keras) (2.1.5)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\nicol\appdata\local\programs\python\python312\lib\site-packages (from rich->keras>=3.5.0->tensorflow<2.20,>=2.19->tf-keras) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\nicol\appdata\local\programs\python\python312\lib\site-packages (from rich->keras>=3.5.0->tensorflow<2.20,>=2.19->tf-keras) (2.18.0)
Requirement already satisfied: mdurl~=0.1 in c:\users\nicol\appdata\local\programs\python\python312\lib\site-packages (from markdown-it-py>=2.2.0->rich->keras>=3.5.0->tensorflow<2.20,>=2.19->tf-keras) (0.1.2)
Requirement already satisfied: torch in c:\users\nicol\appdata\local\programs\python\python312\lib\site-packages (2.7.1)
Requirement already satisfied: filelock in c:\users\nicol\appdata\local\programs\python\python312\lib\site-packages (from torch) (3.18.0)
Requirement already satisfied: typing-extensions>=4.10.0 in c:\users\nicol\appdata\local\programs\python\python312\lib\site-packages (from torch) (4.12.2)
Requirement already satisfied: sympy>=1.13.3 in c:\users\nicol\appdata\local\programs\python\python312\lib\site-packages (from torch) (1.14.0)
Requirement already satisfied: networkx in c:\users\nicol\appdata\local\programs\python\python312\lib\site-packages (from torch) (3.5)
Requirement already satisfied: jinja2 in c:\users\nicol\appdata\local\programs\python\python312\lib\site-packages (from torch) (3.1.4)
Requirement already satisfied: fsspec in c:\users\nicol\appdata\local\programs\python\python312\lib\site-packages (from torch) (2025.5.1)
Requirement already satisfied: setuptools in c:\users\nicol\appdata\local\programs\python\python312\lib\site-packages (from torch) (70.2.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\nicol\appdata\local\programs\python\python312\lib\site-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\nicol\appdata\local\programs\python\python312\lib\site-packages (from jinja2->torch) (2.1.5)

**The Hugging Face Pipeline**
* Makes automation of many NLP tasks possible in 3 lines of code
* Detailed documentation is available [here](https://huggingface.co/transformers/main_classes/pipelines.html)

In [1]:
from transformers import pipeline
import pandas as pd
import numpy as np
from pprint import pprint

c:\Users\nicol\AppData\Local\Programs\Python\Python312\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Note : You might need more libraries or updates to run the cells below, if that is the case, follow the error messages and pip install accordingly. Chat gpt can help you if given the error messages.

### 2.1 Many models tailored to specific tasks

#### 2.1.1 Text classification

Let's select a popular text classification model in the [HF model hub](https://huggingface.co/models?pipeline_tag=text-classification&sort=downloads).

Here we chose "cardiffnlp/twitter-roberta-base-irony".

We will classify text into ironic or non ironic.

In [2]:
pipeline_classification = pipeline("text-classification", model="cardiffnlp/twitter-roberta-base-irony")  # cardiffnlp/twitter-roberta-base-irony, SamLowe/roberta-base-go_emotions

c:\Users\nicol\AppData\Local\Programs\Python\Python312\Lib\site-packages\huggingface_hub\file_download.py:147: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\nicol\.cache\huggingface\hub\models--cardiffnlp--twitter-roberta-base-irony. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)

WARNING:tensorflow:From c:\Users\nicol\AppData\Local\Programs\Python\Python312\Lib\site-packages\tf_keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

Device set to use cpu

Now that we have the model we can pass it a string and have it give us a classification.

Feel free to experiment with different sentences by changing the contents of the variable text

In [3]:
text = "Well that workshop was totally worth my time..."  # "Well that workshop was totally worth my time..."  "This smells weird, I'm not sure if I should eat this ... Yikes, it tasted like old socks!"
output = pipeline_classification(text, top_k=10)
print(output)

[{'label': 'irony', 'score': 0.9424386620521545}, {'label': 'non_irony', 'score': 0.05756136775016785}]

Let's make the output a little cleaner

In [4]:
# make output a bit cleaner
df_output = pd.DataFrame(output)
print(df_output)

       label     score
0      irony  0.942439
1  non_irony  0.057561

As you can see, in a few lines of code and by leveraging an existing model we can classify text as ironic or non ironic. Now you have one more tool in your machine learning toolbox.

Remember that : 'when you only have a hammer everything is a nail'. But if we want to build a house (perform machine learning the right way), we need to use the right tool for the right job.

#### 2.1.2 Machine Translation

* Open source machine translation (MT) models enable you to translate between many different languages without Google Translate.
* [University of Helsinki](https://huggingface.co/Helsinki-NLP) uploaded models for more than 1000 language pairs to the Hugging Face hub
* [Facebook AI](https://huggingface.co/models?search=facebook+m2m) open-sourced several multi-lingual models
* The [EasyNMT library](https://github.com/UKPLab/EasyNMT), provides an easy wrapper for all these models
* Most machine translation models translate between two languages in one direction (e.g. German to English, but not English to German), some can translate in multiple directions.

In [5]:
# translation pipeline docs: https://huggingface.co/transformers/main_classes/pipelines.html#transformers.TranslationPipeline
pipeline_translate = pipeline("translation", model="facebook/m2m100_418M")

c:\Users\nicol\AppData\Local\Programs\Python\Python312\Lib\site-packages\huggingface_hub\file_download.py:147: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\nicol\.cache\huggingface\hub\models--facebook--m2m100_418M. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
Device set to use cpu

M2M100 is a multilingual encoder-decoder (seq-to-seq) model trained for Many-to-Many multilingual translation.

The model that can directly translate between the 9,900 directions of 100 languages.

Here we specify to translate from German 'de' to English 'en'

In [6]:
text = "Ich bin ein Fisch"
pipeline_translate(text, src_lang="de", tgt_lang="en")

[{'translation_text': 'I am a fish'}]

Let's do the same but with and entire wikipedia page in german.

In [7]:
# download any text from wikipedia, via  https://pypi.org/project/wikipedia/
import wikipedia
wikipedia.set_lang("de")

text = wikipedia.summary("Donald Trump").replace('\n', ' ')[:318]
print(f"Original text:\n{text}\n")

# translate the text from wikipedia
text_translated = pipeline_translate(text, src_lang="de", tgt_lang="en")
print(f"Translated text:\n{text_translated[0]['translation_text']}")

Original text:
Donald John Trump [ˈdɑn.əld dʒɑn tɹɐmp] (* 14. Juni 1946 in New York City) ist ein US-amerikanischer Politiker der Republikanischen Partei. Er war von 2017 bis 2021 der 45. und ist seit dem 20. Januar 2025 der 47. Präsident der Vereinigten Staaten. Außerdem ist er Unternehmer und ehemaliger Showmaster. Er gilt als ei

Translated text:
Donald John Trump [ˈdɑn.əld dʒɑn tɔmp] (* 14 June 1946 in New York City) is an American politician of the Republican Party. he was from 2017 to 2021 the 45th and is from 20 January 2025 the 47th President of the United States.

#### 2.1.3 Text Summarization

In [8]:
# docs for summarisation pipeline: https://huggingface.co/transformers/main_classes/pipelines.html#summarizationpipeline
pipeline_summarize = pipeline("summarization", model="sshleifer/distilbart-cnn-12-6")  # sshleifer/distilbart-cnn-12-6 , google/pegasus-cnn_dailymail

c:\Users\nicol\AppData\Local\Programs\Python\Python312\Lib\site-packages\huggingface_hub\file_download.py:147: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\nicol\.cache\huggingface\hub\models--sshleifer--distilbart-cnn-12-6. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
Device set to use cpu

In [15]:
# download any long text from wikipedia, via  https://pypi.org/project/wikipedia/
import wikipedia
wikipedia.set_lang("de")

text_long = wikipedia.summary("Donald Trump").replace('\n', ' ')
print(f"Original text:\n{text_long}\n")

# translate the text from wikipedia
text_summarized = pipeline_summarize(text_long, min_length=5, max_length=30)
print(f"Summarized text:\n{text_summarized[0]['summary_text']}")

Token indices sequence length is longer than the specified maximum sequence length for this model (1416 > 1024). Running this sequence through the model will result in indexing errors

Original text:
Donald John Trump [ˈdɑn.əld dʒɑn tɹɐmp] (* 14. Juni 1946 in New York City) ist ein US-amerikanischer Politiker der Republikanischen Partei. Er war von 2017 bis 2021 der 45. und ist seit dem 20. Januar 2025 der 47. Präsident der Vereinigten Staaten. Außerdem ist er Unternehmer und ehemaliger Showmaster. Er gilt als einer der umstrittensten Politiker der US-Geschichte und ist der erste Präsident, gegen den zwei Amtsenthebungsverfahren angestrengt wurden und der sich nach seiner ersten Präsidentschaft mit mehreren Strafprozessen konfrontiert sieht – unter anderem wegen Verschwörung gegen die USA. Er ist der erste strafrechtlich verurteilte US-Präsident. Trump leitete von 1971 bis 2017 den Mischkonzern The Trump Organization. Trotz eines geerbten Vermögens und mehrerer Insolvenzen in der Immobilienbranche wurde er zum Sinnbild eines erfolgreichen Geschäftsmannes. Ab 2004 wurde er als Gastgeber von The Apprentice populär, einer bis 2015 ausgestrahlten Reality-TV-Sendung. Im Laufe der Jahre unterstützte Trump verschiedene politische Parteien, ist aber seit 1987 mit kurzer Unterbrechung als Mitglied der Republikaner registriert. Als deren Kandidat gewann er die Präsidentschaftswahl 2016 gegen die Demokratin Hillary Clinton. Der Wahlkampf war von Unregelmäßigkeiten gekennzeichnet; seine Kampagne erhielt illegale Unterstützung durch Russland, was später zu einer Sonderermittlung und zu Haftstrafen für Mitglieder seines Wahlkampfteams führte. Er erregte im Wahlkampf mit seinem einfachen Sprachstil, provokanten Äußerungen und radikalen Vorschlägen Aufmerksamkeit. Wahlentscheidend war, dass es Trump trotz zahlreicher Sexismusvorwürfe gegen ihn und offensichtlicher Unwahrheiten gelang, sich als Anwalt der einfachen Leute und der evangelikalen Christen darzustellen. Sein als Trumpismus charakterisierter Politikstil ist eine Mischung aus Populismus, Konservatismus, Libertarismus, Protektionismus (Neomerkantilismus), Wirtschaftsliberalismus, Nationalismus und Isolationismus. Die erste Präsidentschaft Trumps war von zahlreichen Kontroversen geprägt. Zu den vielen Skandalen in Trumps Amtszeit gehört sein Versuch, Waffenhilfe für die Ukraine von Ermittlungen gegen Hunter Biden, den Sohn Joe Bidens, seines Konkurrenten bei der Präsidentschaftswahl 2020, abhängig zu machen. Daher eröffnete das Repräsentantenhaus im Dezember 2019 das erste Impeachment wegen des Vorwurfs des Machtmissbrauchs und der Behinderung des Kongresses. Ein zweites Verfahren wurde im Januar 2021 wegen Anstiftung zum Aufruhr eingeleitet, wenige Tage nach dem Angriff auf das Kapitol durch einen von Trump aufgehetzten Mob. Beide Verfahren endeten mit formalen Freisprüchen durch den republikanisch dominierten Senat. Ein Untersuchungsausschuss des Kongresses kam im Dezember 2022 hingegen zu dem Schluss, die Erstürmung des Kapitols sei von Trump initiiert worden, um sich verfassungswidrig an der Macht zu halten. Ein von der Nachfolgeregierung eingesetzter Sonderermittler kam zum selben Ergebnis und eröffnete im August 2023 ein Strafverfahren gegen Trump. Im selben Monat klagte ihn der Bundesstaat Georgia u. a. wegen versuchter Wahlbeeinflussung an. Schon im März 2023 war er wegen mutmaßlich gefälschter Geschäftsunterlagen und im Juni wegen der Entwendung von Geheimdokumenten angeklagt worden. Trotz der vielen Skandale und juristischen Anklagen wurde Trump für die Präsidentschaftswahl 2024 erneut zum Kandidaten der Republikaner ernannt. Bei einer Wahlkampfveranstaltung im Juli 2024 im US-Bundesstaat Pennsylvania verübte ein Mann mit einer Schusswaffe ein Attentat auf Trump. Dieser überlebte den Anschlag mit einer leichten Verletzung an seinem rechten Ohr. Im November 2024 konnte er die Wahl zum US-Präsidenten gegen Kamala Harris, Spitzenkandidatin der Demokratischen Partei, für sich entscheiden. Donald Trump ist damit nach Grover Cleveland der zweite Präsident, dem nach einer Abwahl später eine Wiederwahl gelang.

IndexError: index out of range in self

#### 2.1.4 Named Entity Recognition

NER is a task that involves identifying and classifying specific entities in text into predefined categories, such as names of people, organizations, locations, dates, and more. 

For example, in the sentence "Apple Inc. was founded by Steve Jobs in California," NER would recognize "Apple Inc." as an organization, "Steve Jobs" as a person, and "California" as a location.

In [12]:
pipeline_ner = pipeline("token-classification", model="dslim/bert-base-NER-uncased", aggregation_strategy="simple")

c:\Users\nicol\AppData\Local\Programs\Python\Python312\Lib\site-packages\huggingface_hub\file_download.py:147: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\nicol\.cache\huggingface\hub\models--dslim--bert-base-NER-uncased. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
Some weights of the model checkpoint at dslim/bert-base-NER-uncased were not used when initializing BertForTokenClassification: ['bert.pooler.dense.bias', 'bert.pooler.dense.weight']
- This IS expected if you are initializing BertForTokenClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForTokenClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Device set to use cpu

In [14]:
import wikipedia
wikipedia.set_lang("de")

text_long = wikipedia.summary("Donald Trump").replace('\n', ' ')

output = pipeline_ner(text_long)

pd.DataFrame(output)

   entity_group     score               word  start   end
0           PER  0.833909  donald john trump      0    17
1           LOC  0.993011      new york city     60    73
2          MISC  0.921308                 us     83    85
3          MISC  0.757686     amerikanischer     86   100
4           ORG  0.499781              ##iti    104   107
..          ...       ...                ...    ...   ...
60         MISC  0.613531             wahlka   1434  1440
61         MISC  0.564275          wahlkampf   1471  1480
62         MISC  0.485355          ##chen sp   1497  1504
63         MISC  0.458379              ##til   1509  1512
64         MISC  0.478951              ##kan   1519  1522

[65 rows x 5 columns]

### 2.2. Universal models

The models mentioned above are designed to excel at a single specific task on a particular dataset. The key advantage of these models is their high performance and accuracy on that specific task and dataset. 

However, in real-world applications, the problems you'll face often require solving slightly different tasks, possibly with varied category definitions or applied to different types of texts.

Universal models can help address this challenge. Although they also focus on one task, the task is general or universal enough that many other tasks can be reformulated into it. Two examples of universal tasks are:

- Natural Language Inference (NLI): A task that can effectively solve a wide range of classification tasks by determining whether a given premise supports, contradicts, or is neutral with respect to a hypothesis.

- Token Generation: An even more universal task that can be applied to solve virtually any text-related task, including translation, summarization, and text completion.

These universal tasks enable the models to be versatile and adaptable to various problems beyond the specific ones they were initially trained on.

#### Zero-shot classification


Zero-shot classification is a technique where a model can categorize data into classes it has never seen before. 

Instead of relying on labeled examples for each class, the model understands the relationship between the input and the class descriptions, allowing it to make accurate predictions without needing specific training on those classes.

In [16]:
pipeline_zeroshot_classification = pipeline("zero-shot-classification", model="MoritzLaurer/mDeBERTa-v3-base-mnli-xnli")

c:\Users\nicol\AppData\Local\Programs\Python\Python312\Lib\site-packages\huggingface_hub\file_download.py:147: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\nicol\.cache\huggingface\hub\models--MoritzLaurer--mDeBERTa-v3-base-mnli-xnli. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
Device set to use cpu

Here we will give the model a list of classes ('payment issues', 'travel advice', 'bug report') for it to classify our string.

In [17]:
text = "Customer: I have not received my reimbursement yet. What the hell is going on?"
classes = ['payment issues', 'travel advice', 'bug report']  # "account opening", "customer complaint"

#text = "I do not think the government is trustworthy anymore. We need to mobilize and resist!"
#classes = ["civil disobedience", "praise of the government", "travel advice"]  # "collective action"

output = pipeline_zeroshot_classification(text, classes, multi_label=True)

pd.DataFrame(data=[output["labels"], output["scores"]], index=["class", "probability"]).T

            class probability
0  payment issues    0.991133
1      bug report    0.076116
2   travel advice    0.018696

## Exercise

Now it is your turn to go to the hugging face library https://huggingface.co/models?pipeline_tag=text-classification&sort=downloads

(you can select on the left menu of the website the type of NLP tasks you want models to perform)

- Find an NLP model that we have not used previously.

- Get some data from wikipedia or elsewhere.

- Perform inference with the model and print the result!

- Comment your code along the way, describe what your model does and what your end goal is from input to output.

Have fun!

In [33]:
# We're using 'tomh/toxigen_hatebert' which is a hate speech detection model.
classifier = pipeline("text-classification", model="tomh/toxigen_hatebert", tokenizer="bert-base-uncased")

c:\Users\nicol\AppData\Local\Programs\Python\Python312\Lib\site-packages\huggingface_hub\file_download.py:147: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\nicol\.cache\huggingface\hub\models--bert-base-uncased. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
Device set to use cpu

In [34]:
# Get a summary of a neutral Wikipedia page and clean the text.
try:
    wiki_summary = wikipedia.summary("Solar System", sentences=1).replace('\n', ' ')
except wikipedia.exceptions.DisambiguationError as e:
    # If the search term is ambiguous, get the first option.
    wiki_summary = wikipedia.summary(e.options[0], sentences=1).replace('\n', ' ')

# Perform inference on the Wikipedia text.
result = classifier(wiki_summary)

# Print the final result.
print(result)

[{'label': 'LABEL_0', 'score': 0.8814210891723633}]

In [37]:
wikipedia.set_lang("de")
# Get a summary of a neutral Wikipedia page and clean the text.
try:
    wiki_summary = wikipedia.summary("Rassismus", sentences=1).replace('\n', ' ')
except wikipedia.exceptions.DisambiguationError as e:
    # If the search term is ambiguous, get the first option.
    wiki_summary = wikipedia.summary(e.options[0], sentences=1).replace('\n', ' ')

# Perform inference on the Wikipedia text.
result = classifier(wiki_summary)

# Print the final result.
print(result)

[{'label': 'LABEL_1', 'score': 0.9370375871658325}]

The tomh/toxigen_hatebert model is a text classifier designed to detect implicit and explicit hate speech. Testing shows that it can accurately identify both a neutral topic, like the Solar System, as non-toxic and a direct, explicitly toxic term, like "Rassismus(german for racism)," as toxic. This suggests that while the model may struggle with nuanced, subtle text (leading to false positives), it's very effective at classifying clear and direct instances of harmful language.